/*
 * List the first and last names of all actors who:
 * 1. have appeared in at least one movie in the "Children" category,
 * 2. but that have never appeared in any movie in the "Horror" category.
 */

SELECT FIRST_NAME, LAST_NAME 
FROM 
(

SELECT FIRST_NAME, LAST_NAME
FROM ACTOR
INNER JOIN FILM_ACTOR
USING (ACTOR_ID)
INNER JOIN FILM
USING (FILM_ID)
INNER JOIN FILM_CATEGORY
USING (FILM_ID)
INNER JOIN CATEGORY 
USING (CATEGORY_ID)
WHERE NAME = 'Children'

) f
WHERE (FIRST_NAME, LAST_NAME) NOT IN
(SELECT FIRST_NAME, LAST_NAME
FROM ACTOR
INNER JOIN FILM_ACTOR
USING (ACTOR_ID)
INNER JOIN FILM
USING (FILM_ID)
INNER JOIN FILM_CATEGORY
USING (FILM_ID)
INNER JOIN CATEGORY
USING (CATEGORY_ID)
WHERE CATEGORY.NAME ILIKE 'Horror'
) 
GROUP BY LAST_NAME, FIRST_NAME
ORDER BY LAST_NAME, FIRST_NAME
